#!/bin/bash

function update_composer() {
    if [ -f "$OPENSHIFT_PHP_DIR/composer/bin/composer" ]; then
        echo 'Updating Composer'
        php $OPENSHIFT_PHP_DIR/composer/bin/composer -q --no-ansi self-update
    fi
}

function check_laravel() {
    if [ -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
            echo 'Dependencies already installed, Moving on...'
    else
            echo 'Hang in there, we are getting ready to Install/Update dependencies'
            echo 'Installing/Updating dependencies'; 
            unset GIT_DIR; 
            cd $OPENSHIFT_REPO_DIR; 
            php $OPENSHIFT_PHP_DIR/composer/bin/composer -q --no-ansi install;
    fi
}
